//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Repository.Helpers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("test.Repository.Helpers.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR ALTER PROCEDURE CreatePolicy
        ///(
        ///	@Description NVARCHAR(255),
        ///	@RiskType INT,
        ///	@StartDate DATETIME,
        ///	@Period INT,
        ///	@State INT,
        ///	@Price DECIMAL,
        ///	@ClientId INT
        ///)AS
        ///BEGIN
        ///	BEGIN TRY
        ///		INSERT INTO Policies
        ///		OUTPUT Inserted.Id AS Id, &apos;&apos; AS ErrorMessage
        ///		VALUES
        ///		(@Description,@RiskType,@StartDate,@Period,@State,@Price,@ClientId)
        ///	 END TRY
        ///    BEGIN CATCH
        ///		SELECT
        ///			0 AS Id,
        ///			ERROR_MESSAGE() AS ErrorMessage
        ///	END CATCH
        ///
        ///END
        ///GO.
        /// </summary>
        internal static string CreateProcPolicy {
            get {
                return ResourceManager.GetString("CreateProcPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR ALTER PROCEDURE CreatePolicyDetail
        ///(
        ///	@PolicyId INT,
        ///	@CoveragePercentage REAL,
        ///	@CoverageId INT
        ///)AS
        ///BEGIN
        ///	BEGIN TRY
        ///		INSERT INTO PolicyDetails
        ///		OUTPUT Inserted.Id AS Id, &apos;&apos; AS ErrorMessage
        ///		VALUES
        ///		(@PolicyId,@CoveragePercentage,@CoverageId)
        ///	END TRY
        ///	BEGIN CATCH
        ///		SELECT
        ///			0 AS Id,
        ///			ERROR_MESSAGE() AS ErrorMessage
        ///	END CATCH
        ///END.
        /// </summary>
        internal static string CreateProcPolicyDetail {
            get {
                return ResourceManager.GetString("CreateProcPolicyDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP PROCEDURE CreatePolicy.
        /// </summary>
        internal static string DropProcPolicy {
            get {
                return ResourceManager.GetString("DropProcPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP PROCEDURE CreatePolicyDetail.
        /// </summary>
        internal static string DropProcPolicyDetail {
            get {
                return ResourceManager.GetString("DropProcPolicyDetail", resourceCulture);
            }
        }
    }
}
